CREATE TABLE IF NOT EXISTS coupon(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  coupon_type VARCHAR(20) NOT NULL,
  coupon_value DECIMAL(10,2) NOT NULL,
  expiration_date TIMESTAMP NOT NULL,
  min_value DECIMAL(10,2),
  active BOOLEAN NOT NULL
);

CREATE TABLE produtos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    preco DECIMAL(10, 2) NOT NULL,
    descricao VARCHAR(255)
);